version: "3"

services:
  dashboard:
    build:
      context: dashboard
    volumes:
      - "./dashboard:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
